/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.collect.Lists;
import java.util.List;

@SuppressWarnings("java:S106")
public class HelloOtus {

    public static void main(String... args) {
        List<String> chars = Lists.newArrayList("A", "B", "C", "D", "E");
        System.out.println(chars);
    }
}
